'use strict';

const fs=require('fs');
const path=require('path');
const assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
const json=name=>JSON.parse(read(name));

const tagIndex=json('hadou_tag_index.json');
const relatedIndex=json('hadou_related_link_index.json');
const statusMasterRaw=json('hadou_status_effects.json');
const statusMaster=Array.isArray(statusMasterRaw)?statusMasterRaw:(statusMasterRaw.items||statusMasterRaw.status_effects||[]);
const statusNames=new Set(statusMaster.map(v=>String(v.name||v.displayName||v.title||'').trim()).filter(Boolean));
const groups=Object.keys(tagIndex.tagGroups||{});

assert.strictEqual(tagIndex.crawlerVersion,'1.1.0.3','tag index must be generated by crawler 1.1.0.3');
assert(tagIndex.qualityAudit?.statusEffectTagAudit?.ok===true,'status-effect tag quality audit must pass');
assert.strictEqual((tagIndex.tagGroups?.['状態変化']||[]).length,statusNames.size,'every status master must be selectable as a tag');
assert(groups.indexOf('状態変化')>=0&&groups.indexOf('状態変化')<groups.indexOf('技能'),'status-effect tags must appear immediately before skill tags');

const itemMap=new Map((tagIndex.items||[]).map(item=>[`${item.category}@@${item.name}`,new Set(item.tags||[])]));
for(const name of statusNames){
  assert(itemMap.get(`status_effects@@${name}`)?.has(`状態変化:${name}`),`status master must own its tag: ${name}`);
}

let checkedOwnerRelations=0;
for(const owner of relatedIndex.items||[]){
  const tags=itemMap.get(`${owner.category}@@${owner.name}`);
  if(!tags)continue;
  for(const relation of owner.related?.statusEffects||[]){
    const name=String(relation.statusEffectName||relation.name||relation.displayName||'').trim();
    if(!statusNames.has(name))continue;
    assert(tags.has(`状態変化:${name}`),`related owner tag missing: ${owner.category} ${owner.name} -> ${name}`);
    checkedOwnerRelations++;
  }
}
assert(checkedOwnerRelations>0,'canonical status-effect owner relations must be checked');

const runtime=read('hado_status_effects.js');
assert(runtime.includes('buildDerivedStatusEffectOwnerTagLookup'),'runtime must retain status-effect tags when older automated data is loaded');
assert(runtime.includes("order.splice(order.indexOf('技能'),0,groupKey)"),'runtime fallback must place status-effect tags before skill tags');
assert(runtime.includes("keys.splice(keys.indexOf('技能'),0,'状態変化')"),'tag picker must place status-effect tags immediately before skill tags');
assert(runtime.includes("key==='状態変化'?(statusEffectTagDisplayName(value)||value):value"),'status-effect tag values must use the same user-facing display names as status search');
assert(runtime.includes('getMatchingTagCandidates(input,limit=16)'),'display-name input must resolve to bounded canonical candidates');
assert(runtime.includes("selectTagCandidate(tag,'candidate-tap')"),'a resolved status-effect candidate must be registered only by explicit selection');

console.log(`3.0.2.0 status-effect tags regression ok: ${statusNames.size} tags / ${checkedOwnerRelations} owner relations`);
